# Generated by Django 3.2.16 on 2022-11-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_mobile_user_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_custom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_indvidual',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_standard',
        ),
        migrations.AddField(
            model_name='user',
            name='company_or_indvidual',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='standard_or_custom',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
