# Generated by Django 3.2.16 on 2022-11-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221101_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_or_indvidual',
            field=models.CharField(max_length=21),
        ),
    ]
